### ISSUE TITLE
Montando o arquivo MP4 |Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by ViniciusRio** [rafaeltmbr/nlw2#1]
Olá, estou usando WSL2 e fui tentar baixar os vídeos, segui os passos de instalação do README.md e na hora de baixar surge essa mensagem e não acaba o processo: Montando o arquivo MP4 |Cannot read property 'message' of undefined

edit: percebi que tem a ver com o ffmpeg, sigo tentando resolver...
edit: acontece a mesma coisa no Fedora 32
edit: na verdade, no método concatAllFiles(), ele cai no catch e não consegue ler o a variavel "err"
edit: videoStitch não tá completando, tô vendo que o método clips() espera um array, porém tá passando um array de array
edit: afirmação anterior é falsa, debuguei novamente e é um array de objetos mesmo

versão do node: 10.19.0
versão do npm: 6.14.4
![prove](https://user-images.githubusercontent.com/34320528/89482667-5b816a00-d768-11ea-9582-3fb370541b6b.png)

**Comment by rafaeltmbr** [comment]
Na variável de ambiente PATH está adicionado o caminho do executável do ffpmeg?

**Comment by rafaeltmbr** [comment]
Oi Vinicius, desculpe a demora.
Não estou conseguindo reproduzir esse erro. Me chama no Discord 'Rafhael#7228' para tentarmos resolver.

**Comment by brunohpaiva** [comment]
Olá, o erro que o Vinicius comentou também aconteceu comigo.

![image](https://user-images.githubusercontent.com/15240571/89646407-19544780-d892-11ea-8441-d7a3b570801c.png)

Node v14.7.0
NPM v6.14.7

**Comment by brunohpaiva** [comment]
Aparentemente consegui extrair o erro que está acontecendo setando a opção `silent` para `false` [nesta linha](https://github.com/rafaeltmbr/nlw2/blob/bc93ffe19572e8e32ea829f4bc829b42d1c4400d/index.js#L152).

```
/bin/sh: -c: linha 0: erro de sintaxe próximo ao token inesperado `('
/bin/sh: -c: linha 0: `ffmpeg -f concat -safe 0 -protocol_whitelist file,http,https,tcp,tls,crypto -i /tmp/tmp-163662V5dewKaIp96.txt -c copy /home/bruno/dev/misc/nlw2/Aula-1-Acelerando-sua-evolucao(1080p).mp4 -y'
```

**Comment by brunohpaiva** [comment]
Criei a pull request  #3 que resolve esse problema.

**Comment by ViniciusRio** [comment]
> Oi Vinicius, desculpe a demora.
> Não estou conseguindo reproduzir esse erro. Me chama no Discord 'Rafhael#7228' para tentarmos resolver.



Eu que demorei agora. Agradecimentos ao @brunohpaiva

**Comment by rafaeltmbr** [comment]
Obrigado @ViniciusRio e @brunohpaiva pela contribuição!
